# Generated by Django 5.0.3 on 2024-03-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_breed_finder",
            "0004_breed_life_esperance_bottom_breed_life_esperance_top",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
